services:
  - type: web
    name: era-75th-anniversary
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: sh start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
